name: sdb_generator
description: A simple Db util for object map db
version: 1.0.8
homepage: http://github.com/huhuang03/sdb.flutter

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  path: ^1.6.4
  build: ^1.2.2
  source_gen: ^0.9.4+6
  code_builder: ^3.2.1
  dart_style: ^1.3.3
  json_serializable: ^3.2.5
  analyzer: '>=0.36.0'
  sdb_annotation:
    path: ../sdb_annotation


dev_dependencies:
  test:
  build_runner:
